micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - '.*'
          allowedMethods:
            - GET
gcp:
  http:
    client:
      auth:
        patterns:
          - /analytics/**
