name: Bump Chocolatey package
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/choco-test.yml"
jobs:
  homebrew:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set the current release version
        id: release_version
#        run: echo ::set-output name=release_version::${GITHUB_REF:11}
        run: echo ::set-output name=release_version::1.2.3
      - name: Download ZIP
#        run: wget -q https://github.com/micronaut-projects/micronaut-starter/releases/download/${{ github.event.release.tag_name }}/mn-win-amd64-${{ github.event.release.tag_name }}.zip -O mn.zip
        run: wget -q https://github.com/micronaut-projects/micronaut-starter/releases/download/v2.0.0.RC1/mn-win-amd64-v2.0.0.RC1.zip -O mn.zip
      - name: Calculate SHA256
        id: sha
        run: |
          s=$(sha256sum mn.zip | awk  '{ print $1 }')
          echo "SHA256 is: $s"
          echo ::set-output name=sha::${s}
      - name: Update versions and checksum
        working-directory: chocolatey
        env:
          SHA: ${{ steps.sha.outputs.sha }}
        run: |
          (Get-Content ./micronaut.nuspec) -replace '<version>.*</version>', "<version>${{ steps.release_version.outputs.release_version }}</version>" | Set-Content ./micronaut.nuspec
          Get-Content ./micronaut.nuspec

          (Get-Content ./tools/chocolateyinstall.ps1) -replace '^\$version.*', "`$version = '${{ steps.release_version.outputs.release_version }}'" | Set-Content ./tools/chocolateyinstall.ps1
          (Get-Content ./tools/chocolateyinstall.ps1) -replace '  checksum\s+=.*', "  checksum      = '$Env:SHA'" | Set-Content ./tools/chocolateyinstall.ps1
          Get-Content ./tools/chocolateyinstall.ps1
      - name: Create package
        working-directory: chocolatey
        run: |
          choco pack
#      - name: Push package
#        working-directory: chocolatey
#        env:
#          API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
#        run: |
#          choco apikey --key $API_KEY --source https://push.chocolatey.org/
#          choco push *.nupkg --source https://push.chocolatey.org/
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Bump Micronaut Chocolatey package to ${{ github.event.release.tag_name }}
#          commit_user_name: micronaut-build
#          commit_user_email: micronaut-build@users.noreply.github.com