name: Bump Chocolatey package
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/choco-test.yml"
jobs:
  chocolatey:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download ZIP, update versions and checksum
        working-directory: chocolatey
        run: |
          #Invoke-RestMethod -Uri https://github.com/micronaut-projects/micronaut-starter/releases/download/${{ github.event.release.tag_name }}/mn-win-amd64-${{ github.event.release.tag_name }}.zip -OutFile 'mn.zip'
          Invoke-RestMethod -Uri https://github.com/micronaut-projects/micronaut-starter/releases/download/v2.0.0.RC1/mn-win-amd64-v2.0.0.RC1.zip -OutFile 'mn.zip'

          $SHA = (Get-FileHash ./mn.zip -Algorithm SHA256).Hash
          echo $SHA

          #$Version = "${{ github.event.release.tag_name }}".substring(1)
          $Version = "v2.0.0.RC1".substring(1)
          echo $Version
          (Get-Content ./micronaut.nuspec) -replace '<version>.*</version>', "<version>$Version</version>" | Set-Content ./micronaut.nuspec
          Get-Content ./micronaut.nuspec

          (Get-Content ./tools/chocolateyinstall.ps1) -replace '^\$version.*', "`$version = '$Version'" | Set-Content ./tools/chocolateyinstall.ps1
          (Get-Content ./tools/chocolateyinstall.ps1) -replace '  checksum\s+=.*', "  checksum      = '$SHA'" | Set-Content ./tools/chocolateyinstall.ps1
          Get-Content ./tools/chocolateyinstall.ps1
      - name: Create package
        working-directory: chocolatey
        run: |
          choco pack
#      - name: Push package
#        working-directory: chocolatey
#        env:
#          API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
#        run: |
#          choco apikey --key $API_KEY --source https://push.chocolatey.org/
#          choco push *.nupkg --source https://push.chocolatey.org/
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Bump Micronaut Chocolatey package to ${{ github.event.release.tag_name }}
#          commit_user_name: micronaut-build
#          commit_user_email: micronaut-build@users.noreply.github.com