name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '14']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew check --continue -x test-core:test -x test-cli:test
      - name: Verify CLI
        run: |
          ./gradlew micronaut-cli:assemble
          cp starter-cli/build/distributions/micronaut-cli-*.zip cli.zip
          unzip cli -d tmp
          mv tmp/micronaut-cli-* tmp/cli
          ./tmp/cli/bin/mn --version
      - name: Publish to JFrog OSS
        if: success() && github.event_name == 'push' && matrix.java == '8' && github.ref == 'refs/heads/master'
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew publish docs
      - name: Publish to Github Pages
        if: success() && github.event_name == 'push' && matrix.java == '8' && github.ref == 'refs/heads/master'
        uses: micronaut-projects/github-pages-deploy-action@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build/docs