on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/homebrew-test.yml"
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Checkout https://github.com/micronaut-projects/homebrew-tap
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: micronaut-projects/homebrew-tap
      - name: Download ZIP
#        run: wget -q https://github.com/micronaut-projects/micronaut-starter/releases/download/${GITHUB_REF:11}/mn-darwin-amd64-${GITHUB_REF:11}.zip -O mn.zip
        run: wget -q https://github.com/micronaut-projects/micronaut-starter/releases/download/v2.0.0.RC1/mn-darwin-amd64-v2.0.0.RC1.zip -O mn.zip
      - name: Calculate SHA256
        id: sha
        run: |
          s=$(sha256sum mn.zip | awk  '{ print $1 }')
          echo "SHA256 is: $s"
          echo ::set-output name=sha::${s}
      - name: Update Cask file
        env:
          SHA: ${{ steps.sha.outputs.sha }}
        run: |
          #sed -i -e "s/version.*/version '${GITHUB_REF:12}'/" Casks/micronaut.rb
          sed -i -e "s/version.*/version '1.2.3'/" Casks/micronaut.rb
          #sed -i -e "s/sha256.*/sha256 '${SHA}'/" Casks/micronaut.rb
          sed -i -e "s/sha256.*/sha256 '4.5.6'/" Casks/micronaut.rb
          cat Casks/micronaut.rb
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Upgrade Micronaut cask to latest version
#          commit_user_name: micronaut-build
#          commit_user_email: micronaut-build@users.noreply.github.com
#
