name: Mac OS X Native
on: [push]
jobs:
  build:
    name: Builds OS X Native CLI
    runs-on: macOS-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Install GraalVM
        env:
          GRAAL_VERSION: 20.0.0
          GRAAL_OS: darwin-amd64
        run: ./install-graal.sh
      - name: Build the JAR
        env:
          JAVA_HOME: ./graalvm/Contents/Home
        run: ./gradlew clean starter-cli:fatJar --no-daemon
      - name: Build Native Image
        run: graalvm/bin/native-image --no-fallback --no-server -cp starter-cli/build/libs/starter-cli-*-all.jar
      - name: Upload Snapshot
        uses: actions/upload-artifact@v1
        with:
          name: mn-osx-snapshot
          path: mn

